QUIET ?= @
CP ?= cp -ar
RM ?= rm -rf
MAKE ?= make
CMAKE ?= cmake
PASS ?= echo -n
SUBMAKE ?= make -w -C
INSTALL_BIN ?= cp -a
INSTALL_DIR ?= mkdir -p
DEBUG ?= --just-print -q
TMP_DIR ?= $(TOPDIR)/.tmp
BUILD_DIR ?= $(TOPDIR)/build_dir
PACKAGE_DIR ?= $(BUILD_DIR)/packages
TARGET_DIR ?= $(BUILD_DIR)/rootfs
TOOLS_DIR ?= $(TOPDIR)/tools
MCONF_DIR ?= $(TOOLS_DIR)/config
SCRIPTS_DIR ?= $(TOOLS_DIR)/scripts
PKG_CONFIGIN_DIR ?= $(TMP_DIR)/config
DL_DIR ?= $(TOPDIR)/download
NPROC ?= $(shell nproc)
PTOOL ?= quilt
OS ?= linux
ARCH ?= x86_64
